# Generated by Django 5.2.1 on 2025-05-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_categoria_alter_item_codigo_produto_item_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
